### ISSUE TITLE
Avatar infront of member name

### ISSUE THREAD

**Issue by DrTheOne** [WildcardSearch/MentionMe#120]
Is it possible to add small avatar of member infront of member name?
Is it possible that avatar size is adjust according to text size?

**Comment by Cu8eeeR** [comment]
Another query... anyway why is it useful, any specific reason?

**Comment by WildcardSearch** [comment]
I can see it from a design perspective, but when you make a mock-up, it begins to become evident that at the average font size, the avatar would be too small to even appreciate:

![Mention With Avatar Mockup](http://i.imgur.com/2OJfPMQ.png)

Also, their is the issue of styling and sizing the avatar. Mention links are necessarily hardcoded. Necessarily because I depend on the markup to find mentions within posts to create alerts. From PHP I cannot predict the size of the font the link text will have. So either admin could choose one size for all mentions, or I could do something hacky with JavaScript to size each mention avatar.

All-in-all, as I have stated on MyBB, I don't think it is a good fit for the plugin.

**Comment by DrTheOne** [comment]
Ok bro. Its your mastery and judgement for it. Without it also its best of the best plugin.
Thank you.

**Comment by WildcardSearch** [comment]
You're welcome. Thank you for using my plugins and giving me feedback.
