### ISSUE TITLE
Popup: Short Names May Not Be Properly Padded

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#150]
![bug1](https://user-images.githubusercontent.com/778890/30391908-6a52c9dc-98bb-11e7-837f-5e06538f7f43.png)

there should be any padding for short usernames (latest maintance version - 13.9.2017)

**Comment by WildcardSearch** [comment]
Are you pointing out that on the right side the name has no padding?

**Comment by Cu8eeeR** [comment]
Yes, exactly... :)

**Comment by WildcardSearch** [comment]
Thanks for the report. I'll look at it this evening.

**Comment by WildcardSearch** [comment]
@Cu8eeeR In my tests, these changes solve the issue. To test you'll have to manually insert `min-width: 120px;` into mentionme.css line 5-- simply updating the files won't work because the upgrade script depends upon the version to be incremented to deploy and I don't change that until immediately prior to release.

**Comment by Cu8eeeR** [comment]
OK, works fine, thank you!
