### ISSUE TITLE
Ability to mention the whole group of users?

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#164]
@WildcardSearch - just a question - is possible somehow (adding support) to mention the whole group of users? For example I wanna mention all of my moderators instead of writing all names separately. It seems to be really useful (you can check this feature here in GitHub). Anyway it would need a permission system and the way how to select which group to mention).

Just a idea, low priority (Quick edit support is the last thing which I miss in MentionMe plugin). Thank you for your feedback!

**Comment by WildcardSearch** [comment]
It really sounds like a great idea. Immediate concerns would be:

- extra queries - afaik MyAlerts doesn't provide a way to insert multiple alerts at once (I need to look again to be sure) so that would mean x queries for every alerted member of the group.
- permissions - It wouldn't be good for users to be able to alert all staff (or all mods/smods/admins/etc) because the potential for abuse would be great imo
- handling ignore list - We would need to determine whether to honor the ignore list when alerting groups

Other than that, I would think there would be need to be a setting added so that admin can select which groups can be mentioned, and which usergroups could mention other entire groups...

What are your thoughts?

Do you see any other contingencies that need to be addressed?

**Comment by Cu8eeeR** [comment]
I agree with you, it would need a lot of changes and additions, but it could have a lot of cons. Maybe in MentionMe v3.3 😄 I think you mentioned everything in your post above.

For me, I am looking forward to Quick edit support, after that it will be perfect :)

**Comment by WildcardSearch** [comment]
You are certainly very welcome. Lets agree to table this for now and we can revisit once 3.2 is out and any bugs that spring up have been squashed.

**Comment by WildcardSearch** [comment]
Let me just put this here while it is on my mind.

RE: Permissions - In the past (ASB), I have learned that administrators will always want more control over permissions. So to me that means that having two settings:

> Groups That Can Be Mentioned (leave blank for all)

and

> Groups That Can Mention (leave blank for all)

...would probably not make everyone happy. I foresee requests of being able to prevent a specific group from mentioned another specific group. Since MyBB has no sort of user-to-user or group-to-group permissions, we would be effectively inventing that system from scratch. Something to think about...

Also, the ignore list. If you have ten moderators in the group and you mention the group, then that is ten queries to retrieve ignore lists for each user being mentioned, ten queries to alert each of those users, and that isn't even counting users which had to be queried (for display/group info) because they weren't active users before the mention...

Lastly, the early conclusion is that MentionMe may need to get an ACP page to handle this (ie. ASB's Manage Sidebox page). Then we could allow admin to control (or disable) group mentioning per group-- AND that would open the door for more precise controls like `x` user cannot mention anyone (abuse), `x` user cannot mention `y` group (hidden group), etc.

@Eldenroot thoughts?

**Comment by Eldenroot** [comment]
My idea, have a "simple" settings for (as you wrote above):
- usergroups that can mention - select one or more / leave blank for all
- usergroups that can be mentioned - select one or more / leave blank for all
- ability to select specific forum/categories where you can use mention the whole usergroup available - select one or more/ leave blank for all

> Lastly, the early conclusion is that MentionMe may need to get an ACP page to handle this (ie. ASB's Manage Sidebox page). Then we could allow admin to control (or disable) group mentioning per group-- AND that would open the door for more precise controls like x user cannot mention anyone (abuse), x user cannot mention y group (hidden group), etc.

Yes, that would be better way but it could be really complicated (anyway it would offer really good way how to set everything for admin's needs). I would start with a simple permission system and then extend it. It would probably bring some bugs which can be ironed out before moving to the advance system.

> Also, the ignore list. If you have ten moderators in the group and you mention the group, then that is ten queries to retrieve ignore lists for each user being mentioned, ten queries to alert each of those users, and that isn't even counting users which had to be queried (for display/group info) because they weren't active users before the mention...

IIRC MyAlerts doesn't support sending multiple alerts at once, which would be really welcomed for that feature... any output @Euan T.

I will think about that and write more if anything... :)

**Comment by WildcardSearch** [comment]
There more I think about this, the more I am leaning toward the thought that this belongs in MyAlerts... @euantorano?

**Comment by euantorano** [comment]
That's probably the best place to do it, yes. I'd need to think about the best way of doing it though.

**Comment by WildcardSearch** [comment]
Yeah it is complex, even in theory.

@Eldenroot It makes more sense to wait for MyAlerts to support group alerts before going ahead with this. Thoughts?
