### ISSUE TITLE
Popup is closed when you add 3 characters (symbols) not matched to any of username

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#188]
How to reproduce:
1) in Quick reply type "@"
2) type 789 for example (or whatever but something what is not in any of username)
3) popup is closed when you type the third symbol

+ how does this work? https://github.com/WildcardSearch/MentionMe/commit/b0e243650e730d463990af96d59a0d83dbf33803

**Comment by WildcardSearch** [comment]
Addressing the main issue: That is intended behavior so that when typing an `@` that isn't intended to be used to mention users, the popup will dismiss itself under certain conditions:

1. The user has typed the minimum amount of characters to search (which coincides with the minimum user name length in ACP) and no names were found.
2. The user has typed more characters than the maximum user name length in ACP.

How would you expect it to behave?

> how does this work? b0e2436

https://api.jquery.com/jQuery.isEmptyObject/

The above jQuery function checks to see if that passed variable (in this case the name cache) is an object and is empty. In other words if the name cache returns an empty set, is corrupted, is deleted or cleared, or (most of the time) the search came up empty.

**Comment by Eldenroot** [comment]
@WildcardSearch - I am sorry, I wasnt at home during weekend. If it is expected, feel free to close. I dont know how to improve that... :(

**Comment by WildcardSearch** [comment]
I'm open to suggestions. It just isn't apparent to me what is wrong with the current method.
